name: Test

on:
  push:

jobs:
  analyze:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Print Warning Message
      run: echo "View commit metadata at ${{ secrets.ARTIFACT_ROOT_URL }}/${{github.sha}}/test.html"
